// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnNxNDQ-EYehb4V19ISwNgaAZF_A2DLr8',
    appId: '1:699680838540:android:a3defac44bdb6b2a9a7ca9',
    messagingSenderId: '699680838540',
    projectId: 'flutter-pre-16628',
    databaseURL: 'https://flutter-pre-16628-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-pre-16628.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATCsaTn3GGi-knyZqMq7OF7X1-uN9kBFs',
    appId: '1:699680838540:ios:603ff855f0b0b2c69a7ca9',
    messagingSenderId: '699680838540',
    projectId: 'flutter-pre-16628',
    databaseURL: 'https://flutter-pre-16628-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-pre-16628.appspot.com',
    iosBundleId: 'com.chat.chatApp',
  );
}
